#!/bin/bash

NODES=${1:-3}

cat > docker-compose.yml <<EOF
services:
  login:
    build: .
    container_name: login01
    hostname: login01
    ports:
      - "2222:22"
    environment:
      ROLE: login
    volumes:
      - home:/home/dev
      - ./cluster_key:/home/dev/.ssh/id_ed25519:ro
      - ./authorized_keys:/home/dev/.ssh/authorized_keys:ro
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./munge.key:/tmp/munge.key:ro
    command: ["/entrypoint.sh"]
    networks:
      - cluster
EOF

for i in $(seq 1 "$NODES"); do
cat >> docker-compose.yml <<EOF

  node$i:
    build: .
    container_name: node$i
    hostname: node$i
    environment:
      ROLE: compute
    volumes:
      - home:/home/dev
      - ./authorized_keys:/home/dev/.ssh/authorized_keys:ro
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./munge.key:/tmp/munge.key:ro
    command: ["/entrypoint.sh"]
    networks:
      - cluster
EOF
done

cat >> docker-compose.yml <<EOF

volumes:
  home:

networks:
  cluster:
    driver: bridge
EOF

cat > slurm.conf <<EOF
ClusterName=cluster

SlurmUser=slurm

AuthType=auth/munge
SlurmctldHost=login01

ProctrackType=proctrack/pgid
TaskPlugin=task/none
JobAcctGatherType=jobacct_gather/none

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

StateSaveLocation=/slurm/state
SlurmdSpoolDir=/slurm/spool

NodeName=node[1-${NODES}] CPUs=4 State=UNKNOWN
PartitionName=debug Nodes=node[1-${NODES}] Default=YES MaxTime=INFINITE State=UP
EOF

docker compose up